name = "Flintheart Glomgold - Lone Cheater"
type = "Character"
cost = 4
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_1121277f1b454321be2740185a61c1c7.avif?1709690747"
max_copies = 4
inkwell = true
strength = 3
willpower = 4
lore = 2
classifications = ["Storyborn", "Villain"]
text = "THEY'LL NEVER SEE IT COMING! During your turn, this character gains Evasive. (They can challenge characters with Evasive.)"
