name = "Helga Sinclair - Right-Hand Woman"
type = "Character"
cost = 3
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_7cc596998ca54d02b163996079f18414.avif?1709690747"
max_copies = 4
inkwell = true
strength = 2
willpower = 4
lore = 1
classifications = ["Storyborn", "Villain"]
keywords = ["Challenger 2"]
text = "Challenger +2 (While challenging, this character gets +2 {S}.)"
