name = "Kida - Royal Warrior"
type = "Character"
cost = 2
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_3cead19199044fd5bb448a13f2ce8189.avif?1709690747"
max_copies = 4
inkwell = true
strength = 2
willpower = 3
lore = 1
classifications = ["Storyborn", "Hero", "Princess"]
keywords = ["Bodyguard"]
text = "Bodyguard (This character may enter play exerted. An opposing character who challenges one of your characters must choose one with Bodyguard if able.)"
