name = "Boss's Orders"
type = "Action"
cost = 1
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_d1f9df5413484ad6975ba55243e4804e.avif?1709690747"
max_copies = 4
inkwell = true
text = "Chosen character gains Support this turn. (Whenever they quest, you may add their {S} to another chosen character's {S} this turn.)"
