name = "Heal What Has Been Hurt"
type = "Song"
cost = 3
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_c6998d2082d348b18f01e8a90afde5f1.avif?1709690747"
max_copies = 4
inkwell = true
text = "(A character with cost 3 or more can {E} to sing this song for free.)\nRemove up to 3 damage from chosen character. Draw a card."
