name = "Magic Broom - Dancing Duster"
type = "Character"
cost = 6
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_bf44f442286c4b5fa783412ae85c3b58.avif?1709690747"
max_copies = 4
strength = 3
willpower = 3
lore = 1
classifications = ["Dreamborn", "Broom"]
text = "POWER CLEAN When you play this character, if you have a Sorcerer character in play, you may exert chosen opposing character. They can't ready at the start of their next turn."
