name = "Kida - Protector of Atlantis"
type = "Character"
cost = 5
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_edeffddbafd54b319a0f9bf65a1480b5.avif?1709690747"
max_copies = 4
inkwell = true
strength = 3
willpower = 5
lore = 2
classifications = ["Floodborn", "Hero", "Princess"]
keywords = ["Shift 3"]
text = "Shift 3 (You may pay 3 {I} to play this on top of one of your characters named Kida.)\nPERHAPS WE CAN SAVE OUR FUTURE When you play this character, all characters get -3 {S} until the start of your next turn."
