name = "Cursed Merfolk - Ursula's Handiwork"
type = "Character"
cost = 1
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_25aa34175eeb4f30bbb9199f46040395.avif?1709690747"
max_copies = 4
strength = 0
willpower = 1
lore = 2
classifications = ["Storyborn"]
text = "POOR SOULS Whenever this character is challenged, each opponent chooses and discards a card."
