name = "Milo Thatch - King of Atlantis"
type = "Character"
cost = 7
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_1ab44dc7b1b1406ea256eb308fb857f5.avif?1709690747"
max_copies = 4
strength = 4
willpower = 4
lore = 3
classifications = ["Floodborn", "Hero", "King"]
keywords = ["Shift 4"]
text = "Shift 4 (You may pay 4 {I} to play this on top of one of your characters named Milo Thatch.)\nTAKE THEM BY SURPRISE When this character is banished, return all opposing characters to their players' hands."
