name = "Prince John - Phony King"
type = "Character"
cost = 5
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_1af5228c0d75411ebc9eccf5cae1c086.avif?1709690747"
max_copies = 4
strength = 2
willpower = 4
lore = 2
classifications = ["Storyborn", "Villain", "Prince"]
text = "COLLECT TAXES Whenever this character quests, each opponent with more lore than you loses 2 lore."
