name = "Wreck-it Ralph - Raging Wrecker"
type = "Character"
cost = 7
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_cb5f4cea3a664d12952b12a0a30fbbf3.avif?1770259662"
max_copies = 4
strength = 3
willpower = 4
lore = 3
classifications = ["Storyborn", "Hero", "Whisper"]
keywords = ["Boost 1"]
text = "Boost 1 {I} (Once during your turn, you may pay 1 {I} to put the top card of your deck facedown under this character.)\nPOWERED UP This character gets +1 {S} for each card under him.\nWHO'S COMIN' WITH ME? When this character is banished, banish all characters with {S} equal to or less than the {S} he had in play."
