name = "Grab Your Bow"
type = "Song"
cost = 5
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_4bf208bd16b043ac8eb27209b522c3c6.avif?1770259790"
max_copies = 4
text = "(A character with cost 5 or more can {E} to sing this song for free.)\nBanish up to 2 chosen characters with 2 {S} or less."
