name = "Darkwing's Chair Set"
type = "Item"
cost = 3
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_2663ccb2084547c0a55220f63f46a36c.avif?1770259956"
max_copies = 4
text = "SECRET ENTRANCE When you play this item, you may put the top card of your deck into your inkwell facedown and exerted.\nSUDDEN SPIN {E}, Banish this item — Remove up to 2 damage from chosen character. If a character named Darkwing Duck is chosen, remove up to 4 damage instead."
