name = "Ling - Snow Warrior"
type = "Character"
cost = 3
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_00eb4b66a7f945adaa15ca341179bbf7.avif?1770259536"
max_copies = 4
inkwell = true
strength = 2
willpower = 3
lore = 2
classifications = ["Storyborn", "Ally"]
text = "BUILDING MUSCLES 1 {I} — Chosen character gets +1 {S} this turn."
