name = "David - Protective Snowboarder"
type = "Character"
cost = 2
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_b5db84fe81624162968c99d1ca9ee5af.avif?1770259238"
max_copies = 4
inkwell = true
strength = 1
willpower = 4
lore = 1
classifications = ["Storyborn", "Ally"]
keywords = ["Bodyguard"]
text = "Bodyguard (This character may enter play exerted. An opposing character who challenges one of your characters must choose one with Bodyguard if able.)"
