name = "Ariel - Ethereal Voice"
type = "Character"
cost = 4
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_43c967fc98154d6f86b8ac05b8953c10.avif?1761752005"
max_copies = 4
inkwell = true
strength = 3
willpower = 4
lore = 2
classifications = ["Storyborn", "Hero", "Princess", "Whisper"]
text = "Boost 1 {I} (Once during your turn, you may pay 1 {I} to put the top card of your deck facedown under this character.)\nCOMMAND PERFORMANCE Once during your turn, whenever you play a song, if there's a card under this character, you may draw a card."
