name = "The Headless Horseman - Relentless Spirit"
type = "Character"
cost = 4
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_27747f32e8a3479cac5b138f81f0dff0.avif?1761764928"
max_copies = 4
inkwell = true
strength = 4
willpower = 4
lore = 1
classifications = ["Storyborn", "Villain"]
keywords = ["Bodyguard"]
text = "Bodyguard (This character may enter play exerted. An opposing character who challenges one of your characters must choose one with Bodyguard if able.)"
