name = "Putting It All Together"
type = "Action"
cost = 2
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_5c1f05cc2e5c4dae84e51404de23df74.avif?1761764932"
max_copies = 4
inkwell = true
text = "Chosen opposing character can't challenge during their next turn. Draw a card."
