//! Every committed per-set card file under `cards/sets/` must parse via the
//! engine's own TOML loader and yield a non-zero number of cards.
//!
//! The files are generated by `cards/scripts/from_lorcast.py` from an external
//! Lorcast research dump (which is *not* committed); this test guards that the
//! generated, committed TOML always loads.

use std::fs;
use std::path::Path;

use lorcana_engine::load_toml;

#[test]
fn every_set_file_loads_with_cards() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("cards/sets");
    let mut checked = 0usize;
    for entry in fs::read_dir(&dir).expect("read cards/sets") {
        let path = entry.expect("dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }
        let contents =
            fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let defs = load_toml(&contents).unwrap_or_else(|e| panic!("load {}: {e}", path.display()));
        assert!(
            !defs.is_empty(),
            "{} should contain at least one card",
            path.display()
        );
        // Backfilled metadata: every card carries 1-2 ink types and an image.
        for def in &defs {
            let n = def.ink_types().len();
            assert!(
                (1..=2).contains(&n),
                "{} card {:?} has {n} ink types (expected 1-2)",
                path.display(),
                def.names().first()
            );
            assert!(
                def.image().is_some(),
                "{} card {:?} is missing an image",
                path.display(),
                def.names().first()
            );
        }
        checked += 1;
    }
    assert!(
        checked > 0,
        "expected at least one set file in {}",
        dir.display()
    );
}
