name = "Prince Eric - Seafaring Prince"
type = "Character"
cost = 3
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_59c6d7badfc34295857ca0743b40ceca.avif?1716052430"
max_copies = 4
inkwell = true
strength = 3
willpower = 3
lore = 1
classifications = ["Dreamborn", "Hero", "Prince"]
keywords = ["Bodyguard"]
text = "Bodyguard (This character may enter play exerted. An opposing character who challenges one of your characters must choose a character with Bodyguard if able.)"
