name = "Tick-Tock - Ever-Present Pursuer"
type = "Character"
cost = 6
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_8702d63bf6f64674b5871fa1373a1221.avif?1716052430"
max_copies = 4
inkwell = true
strength = 4
willpower = 7
lore = 1
classifications = ["Storyborn", "Ally"]
keywords = ["Evasive"]
text = "Evasive (Only characters with Evasive can challenge this character.)"
