name = "Second Star to the Right"
type = "Song"
cost = 10
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_2712b680c8c541bc868af5e0e208d295.avif?1716052430"
max_copies = 4
keywords = ["Sing Together 10"]
text = "Sing Together 10 (Any number of your or your teammates' characters with total cost 10 or more may {E} to sing this song for free.)\nChosen player draws 5 cards."
