name = "Rapunzel - High Climber"
type = "Character"
cost = 5
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_963d4566252a47b2ae12307309ab2022.avif?1747509028"
max_copies = 4
inkwell = true
strength = 2
willpower = 5
lore = 2
classifications = ["Dreamborn", "Hero", "Princess"]
keywords = ["Evasive"]
text = "Evasive (Only characters with Evasive can challenge this character.)\nWRAPPED UP Whenever this character quests, chosen opposing character can't quest during their next turn."
