name = "Archimedes - Resourceful Owl"
type = "Character"
cost = 3
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_bf2471b2597f495db6b088a5705d4502.avif?1747509096"
max_copies = 4
inkwell = true
strength = 2
willpower = 2
lore = 2
classifications = ["Storyborn", "Ally"]
text = "YOU DON'T NEED THAT When you play this character, you may banish chosen item.\nNOW, THAT'S NOT BAD During your turn, whenever an item is banished, you may draw a card, then choose and discard a card."
