name = "Heads Held High"
type = "Song"
cost = 6
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_9a3f7df243294b3f9247aec8128be37a.avif?1747509425"
max_copies = 4
inkwell = true
keywords = ["Sing Together 6"]
text = "Sing Together 6 (Any number of your or your teammates' characters with total cost 6 or more may {E} to sing this song for free.) \nRemove up to 3 damage from any number of chosen characters. All opposing characters get -3 {S} this turn."
