name = "Atitaya - Fang General"
type = "Character"
cost = 7
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_a4e5d72ce815494eb8647bbe7aa33454.avif?1747509450"
max_copies = 4
inkwell = true
strength = 7
willpower = 7
lore = 3
classifications = ["Storyborn", "Ally"]
