name = "General Li - Head of the Imperial Army"
type = "Character"
cost = 3
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_a0a9f2ad02684ebd877ed697c7ce1188.avif?1747509474"
max_copies = 4
inkwell = true
strength = 2
willpower = 4
lore = 1
classifications = ["Storyborn", "Mentor"]
keywords = ["Resist 1"]
text = "Resist +1 (Damage dealt to this character is reduced by 1.)"
