name = "Genie - Satisfied Dragon"
type = "Character"
cost = 3
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_1a915d634d8048febe7e324fa0c4730b.avif?1747509482"
max_copies = 4
inkwell = true
strength = 3
willpower = 4
lore = 1
classifications = ["Storyborn", "Ally", "Dragon"]
text = "BUG CATCHER During your turn, this character gains Evasive. (They can challenge characters with Evasive.)"
