name = "Calhoun - Hard-Nosed Leader"
type = "Character"
cost = 6
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_6fe60149cee34a1e8c979d598251e279.avif?1747507327"
max_copies = 4
inkwell = true
strength = 4
willpower = 5
lore = 2
classifications = ["Storyborn", "Hero"]
keywords = ["Bodyguard"]
text = "Bodyguard (This character may enter play exerted. An opposing character who challenges one of your characters must choose one with Bodyguard if able.)\nLOOT DROP When this character is banished, gain 1 lore."
