name = "Pinocchio - Strings Attached"
type = "Character"
cost = 4
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_a0a931cb7b6248b3a56080e7f39b7e2b.avif?1747508668"
max_copies = 4
inkwell = true
strength = 0
willpower = 4
lore = 2
classifications = ["Storyborn", "Hero"]
keywords = ["Evasive"]
text = "Evasive (Only characters with Evasive can challenge this character.)\nGOT TO KEEP REAL QUIET Once during your turn, whenever you ready this character, you may draw a card."
