name = "Chaca - Junior Chipmunk"
type = "Character"
cost = 4
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_4be229ca7b79419896cf9bea3c11ee66.avif?1747508938"
max_copies = 4
inkwell = true
strength = 3
willpower = 3
lore = 1
classifications = ["Storyborn", "Ally"]
text = "IN CAHOOTS When you play this character, if you have a character named Tipo in play, chosen opposing character gains Reckless during their next turn. (They can't quest and must challenge if able.)"
