name = "Maleficent - Monstrous Dragon"
type = "Character"
cost = 9
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_a79483514b7249cbb16c12a9ef1d065d.avif?1773508713"
max_copies = 4
inkwell = true
strength = 7
willpower = 5
lore = 2
classifications = ["Storyborn", "Villain", "Dragon"]
text = "DRAGON FIRE When you play this character, you may banish chosen character."
