name = "Powerline - World's Greatest Rock Star"
type = "Character"
cost = 6
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_3a5f83e2f53f4bf0b0d621014cd8f6cf.avif?1755540821"
max_copies = 4
inkwell = true
strength = 6
willpower = 4
lore = 2
classifications = ["Floodborn"]
keywords = ["Shift 4"]
text = "Shift 4 {I} (You may pay 4 {I} to play this on top of one of your characters named Powerline.)\nSinger 9\nMASH-UP Once during your turn, whenever this character sings a song, look at the top 4 cards of your deck. You may reveal a song card with cost 9 or less and play it for free. Put the rest on the bottom of your deck in any order."
