name = "Mulan - Elite Archer"
type = "Character"
cost = 6
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_44fe3bead4bf40f79163468a4fd647e5.avif?1755540935"
max_copies = 4
inkwell = true
strength = 2
willpower = 6
lore = 2
classifications = ["Floodborn", "Hero", "Princess"]
keywords = ["Shift 5"]
text = "Shift 5 {I} (You may pay 5 {I} to play this on top of one of your characters named Mulan.)\nSTRAIGHT SHOOTER When you play this character, if you used Shift to play her, she gets +3 {S} this turn.\nTRIPLE SHOT During your turn, whenever this character deals damage to another character in a challenge, deal the same amount of damage to up to 2 other chosen characters."
