name = "Medallion Weights"
type = "Item"
cost = 2
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_568ccd26d0fa49ac94a67b49e599930d.avif?1755540987"
max_copies = 4
inkwell = true
text = "DISCIPLINE AND STRENGTH {E}, 2 {I} — Chosen character gets +2 {S} this turn. Whenever they challenge another character this turn, you may draw a card."
