name = "Huey - Savvy Nephew"
type = "Character"
cost = 2
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_5008e2e0ceb04bb9878d2590c92b32ee.avif?1755541025"
max_copies = 4
inkwell = true
strength = 2
willpower = 2
lore = 1
classifications = ["Dreamborn", "Ally"]
keywords = ["Support"]
text = "Support (Whenever this character quests, you may add their {S} to another chosen character's {S} this turn.)\nTHREE NEPHEWS Whenever this character quests, if you have characters named Dewey and Louie in play, you may draw 3 cards."
