name = "One Jump Ahead"
type = "Song"
cost = 2
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_5bc8b5538ba94d59979d7ebb574c0bd2.avif?1755541211"
max_copies = 4
text = "(A character with cost 2 or more can {E} to sing this song for free.)\nPut the top card of your deck into your inkwell facedown and exerted."
