name = "Eeyore - Overstuffed Donkey"
type = "Character"
cost = 5
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_214cf74b7c2e445282009e4d227b2519.avif?1755541311"
max_copies = 4
inkwell = true
strength = 4
willpower = 5
lore = 1
classifications = ["Storyborn", "Ally"]
keywords = ["Resist 1"]
text = "Resist +1 (Damage dealt to this character is reduced by 1.)"
