name = "Lawrence - Jealous Manservant"
type = "Character"
cost = 3
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_9cba34a84bf04721aefd09dc1e87cb3a.avif?1755541330"
max_copies = 4
inkwell = true
strength = 0
willpower = 4
lore = 2
classifications = ["Storyborn", "Ally"]
text = "PAYBACK While this character has no damage, he gets +4 {S}."
