name = "Maui's Place of Exile - Hidden Island"
type = "Location"
cost = 2
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_f2169b618849493a969102f760825622.avif?1755541451"
max_copies = 4
inkwell = true
move_cost = 1
willpower = 5
lore = 0
text = "ISOLATED Characters gain Resist +1 while here. (Damage dealt to them is reduced by 1.)"
