name = "Elsa - Spirit of Winter"
type = "Character"
cost = 8
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_096f0a6be34a4134aaa682c768cceeec.avif?1755741240"
max_copies = 4
strength = 4
willpower = 6
lore = 3
classifications = ["Floodborn", "Hero", "Queen", "Sorcerer"]
keywords = ["Shift 6"]
text = "Shift 6 {I} (You may pay 6 {I} to play this on top of one of your characters named Elsa.)\nDEEP FREEZE When you play this character, exert up to 2 chosen characters. They can't ready at the start of their next turn."
