"""Shared helpers for the per-card TOML layout (cards/{set}/{collector}.toml).

A card's *structured* fields + printed `text` are the engine's source of truth;
DSL abilities are authored separately (an AI pass) and are **not** emitted here.
Both the per-card files and the combined `cards/sets/{set}.toml` are rendered by
`emit_card` so the two representations stay byte-consistent.
"""

# Canonical field order, matching the committed layout.
_CHAR_STATS = ("strength", "willpower", "lore")
_LOC_STATS = ("move_cost", "willpower", "lore")


def toml_escape(value: str) -> str:
    """Escape a string for a TOML basic (double-quoted) string."""
    out = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _str_array(values) -> str:
    return "[" + ", ".join(toml_escape(v) for v in values) + "]"


def normalize(card: dict) -> dict:
    """Project a parsed card table onto the structured fields we keep (drops any
    authored ability sub-tables: abilities / activated / statics)."""
    keep = (
        "name", "type", "cost", "ink", "image", "max_copies", "inkwell",
        "strength", "willpower", "lore", "move_cost", "classifications",
        "keywords", "text",
    )
    return {k: card[k] for k in keep if k in card}


def emit_card(card: dict, top_level: bool) -> str:
    """Render one card. With ``top_level`` the fields sit at the file root (one
    card per file); otherwise they form a ``[[card]]`` block for a set file."""
    lines = [] if top_level else ["[[card]]"]
    lines.append(f"name = {toml_escape(card['name'])}")
    lines.append(f"type = {toml_escape(card['type'])}")
    lines.append(f"cost = {int(card['cost'])}")
    lines.append(f"ink = {_str_array(card.get('ink', []))}")
    lines.append(f"image = {toml_escape(card['image'])}")
    # Default deck limit is 4 (§); always emit it so the AI pass can adjust
    # per card (e.g. Dalmatian Puppy = 99).
    lines.append(f"max_copies = {int(card.get('max_copies', 4))}")
    if card.get("inkwell"):
        lines.append("inkwell = true")
    stats = _CHAR_STATS if card["type"] == "Character" else (
        _LOC_STATS if card["type"] == "Location" else ()
    )
    for s in stats:
        if s in card:
            lines.append(f"{s} = {int(card[s])}")
    if card.get("classifications"):
        lines.append(f"classifications = {_str_array(card['classifications'])}")
    if card.get("keywords"):
        lines.append(f"keywords = {_str_array(card['keywords'])}")
    if card.get("text"):
        lines.append(f"text = {toml_escape(card['text'])}")
    return "\n".join(lines)


def set_header(code: str) -> str:
    """The standard generated-file header for a combined set file."""
    return (
        f"# Cards for Lorcana set {code}, in the engine's own TOML format.\n"
        "# Generated by cards/scripts/from_lorcast.py from a Lorcast research\n"
        "# dump (the external dataset itself is not committed). Structured\n"
        "# fields + supported keywords only; text-based abilities are authored\n"
        "# by hand via the effect DSL.\n\n"
    )
