name = "Mickey Mouse - Brave Little Tailor"
type = "Character"
cost = 8
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_a0a1e1bb99794f04991929ced6001ae8.avif?1723596439"
max_copies = 4
inkwell = true
strength = 5
willpower = 5
lore = 4
classifications = ["Dreamborn", "Hero"]
keywords = ["Evasive"]
text = "Evasive (Only characters with Evasive can challenge this character.)"
