name = "Pegasus - Gift for Hercules"
type = "Character"
cost = 1
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_6fdc49b664264148aab790e83e3466a7.avif?1776533209"
max_copies = 4
inkwell = true
strength = 1
willpower = 1
lore = 1
classifications = ["Storyborn", "Ally"]
keywords = ["Evasive"]
text = "Evasive (Only characters with Evasive can challenge this character.)"
