name = "Li Shang - Newly Promoted"
type = "Character"
cost = 3
ink = ["Ruby", "Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_82fe7f4aeec649bbba476dddb838a620.avif?1740589632"
max_copies = 4
strength = 2
willpower = 3
lore = 1
classifications = ["Storyborn", "Hero", "Captain"]
text = "I WON'T LET YOU DOWN This character can challenge ready characters.\nBIG RESPONSIBILITY While this character is damaged, he gets +2 {S}."
