name = "Robin Hood - Eye for Detail"
type = "Character"
cost = 3
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_35c7b95d00c14614857dcb98e4fb99e1.avif?1740589780"
max_copies = 4
inkwell = true
strength = 3
willpower = 3
lore = 1
classifications = ["Storyborn", "Hero"]
keywords = ["Support"]
text = "Support (Whenever this character quests, you may add their {S} to another chosen character's {S} this turn.)"
