name = "Restoring Atlantis"
type = "Action"
cost = 5
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_7dec0a0d27274499a97466ef6f6a6c06.avif?1740590271"
max_copies = 4
text = "Your characters can't be challenged until the start of your next turn."
