name = "Anna - Ice Breaker"
type = "Character"
cost = 4
ink = ["Amethyst", "Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_b46a014c04334b358578cee5fbd9444f.avif?1740589384"
max_copies = 4
inkwell = true
strength = 2
willpower = 3
lore = 2
classifications = ["Dreamborn", "Hero", "Queen", "Sorcerer"]
keywords = ["Support"]
text = "Support (Whenever this character quests, you may add their {S} to another chosen character's {S} this turn.)\nWINTER AMBUSH When you play this character, chosen opposing character can't ready at the start of their next turn."
