name = "Fix-It Felix, Jr. - Trusty Builder"
type = "Character"
cost = 3
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_e300981771704026815250b876ae28be.avif?1723917209"
max_copies = 4
inkwell = true
strength = 2
willpower = 4
lore = 1
classifications = ["Storyborn", "Hero"]
keywords = ["Bodyguard"]
text = "Bodyguard (This character may enter play exerted. An opposing character who challenges one of your characters must choose one with Bodyguard if able.)"
