name = "Tropical Rainforest - Jaguar Lair"
type = "Location"
cost = 3
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_85d29b6399cc45b696b6f1e9abe19910.avif?1723917209"
max_copies = 4
inkwell = true
move_cost = 1
willpower = 6
lore = 1
text = "SNACK TIME Opposing damaged characters gain Reckless. (They can't quest and must challenge if able.)"
