name = "Snowanna Rainbeau - Cool Competitor"
type = "Character"
cost = 3
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_0af4496693f64685885b27455c69e385.avif?1723917209"
max_copies = 4
strength = 2
willpower = 4
lore = 1
classifications = ["Storyborn", "Ally", "Racer"]
keywords = ["Rush"]
text = "Rush (This character can challenge the turn they're played.)"
