name = "Taffyta Muttonfudge - Crowd Favorite"
type = "Character"
cost = 1
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_4a0125f47df34b3c9f0f097e0cc68c84.avif?1723917209"
max_copies = 4
inkwell = true
strength = 1
willpower = 2
lore = 1
classifications = ["Storyborn", "Ally", "Racer"]
text = "SHOWSTOPPER When you play this character, if you have a location in play, each opponent loses 1 lore."
