name = "Pete - Steamboat Rival"
type = "Character"
cost = 7
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_3c2769ada879468487b74479a921bc27.avif?1723917209"
max_copies = 4
inkwell = true
strength = 6
willpower = 6
lore = 2
classifications = ["Storyborn", "Villain"]
text = "SCRAM! When you play this character, if you have another character named Pete in play, you may banish chosen opposing character."
