name = "Taffyta Muttonfudge - Sour Speedster"
type = "Character"
cost = 4
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_b486db00d41f4888984650e72cc36b00.avif?1723917209"
max_copies = 4
inkwell = true
strength = 3
willpower = 3
lore = 1
classifications = ["Floodborn", "Ally", "Racer"]
keywords = ["Shift 2"]
text = "Shift 2 (You may pay 2 {I} to play this on top of one of your characters named Taffyta Muttonfudge.)\nNEW ROSTER Once per turn, when this character moves to a location, gain 2 lore."
