name = "Who's With Me?"
type = "Action"
cost = 3
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_534a9b86f32b472ab15ec30d254d76e3.avif?1723917209"
max_copies = 4
inkwell = true
text = "Your characters get +2 {S} this turn.\nWhenever one of your characters with Reckless challenges another character this turn, gain 2 lore."
