name = "Mirabel Madrigal - Family Gatherer"
type = "Character"
cost = 5
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_7c261f64006d414180bf53ea7ae2f467.avif?1723917209"
max_copies = 4
inkwell = true
strength = 5
willpower = 5
lore = 5
classifications = ["Storyborn", "Hero", "Madrigal"]
text = "NOT WITHOUT MY FAMILY You can't play this character unless you have 5 or more characters in play."
