name = "HeiHei - Protective Rooster"
type = "Character"
cost = 5
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_3c5807144992461aa42226464a5cd693.avif?1723917209"
max_copies = 4
inkwell = true
strength = 4
willpower = 5
lore = 2
classifications = ["Dreamborn", "Ally"]
keywords = ["Bodyguard"]
text = "Bodyguard (This character may enter play exerted. An opposing character who challenges one of your characters must choose one with Bodyguard if able.)"
