name = "Simba - Son of Mufasa"
type = "Character"
cost = 6
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_6b0937a994d6436ca4ffaf3e6304534b.avif?1723917209"
max_copies = 4
inkwell = true
strength = 3
willpower = 5
lore = 1
classifications = ["Floodborn", "Hero", "King"]
keywords = ["Shift 4"]
text = "Shift 4 (You may pay 4 {I} to play this on top of one of your characters named Simba.)\nFEARSOME ROAR When you play this character, you may banish chosen item or location."
