name = "Shield of Arendelle"
type = "Item"
cost = 1
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_c54910dbfc304bb5b4e71639858ceb82.avif?1723917209"
max_copies = 4
inkwell = true
text = "DEFLECT Banish this item — Chosen character gains Resist +1 until the start of your next turn. (Damage dealt to them is reduced by 1.)"
