name = "Merlin - Turtle"
type = "Character"
cost = 4
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_830fee590a4e49c1a54622779b4380c3.avif?1723917209"
max_copies = 4
inkwell = true
strength = 3
willpower = 3
lore = 2
classifications = ["Storyborn", "Mentor", "Sorcerer"]
text = "GIVE ME TIME TO THINK When you play this character and when he leaves play, look at the top 2 cards of your deck. Put one on the top of your deck and the other on the bottom."
