name = "Olaf - Happy Passenger"
type = "Character"
cost = 9
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_bb8f3a2d154346dc8e21ef6fea46a1f0.avif?1723917209"
max_copies = 4
strength = 6
willpower = 6
lore = 3
classifications = ["Storyborn", "Ally"]
keywords = ["Evasive"]
text = "CLEAR THE PATH For each exerted character opponents have in play, you pay 1 {I} less to play this character.\nEvasive (Only characters with Evasive can challenge this character.)"
