name = "Vanellope von Schweetz - Sugar Rush Champ"
type = "Character"
cost = 1
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_d3dd900e88304c778c319c8facd2c8f2.avif?1723917209"
max_copies = 4
inkwell = true
strength = 2
willpower = 2
lore = 1
classifications = ["Storyborn", "Hero", "Princess", "Racer"]
