name = "Fauna - Good Fairy"
type = "Character"
cost = 5
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_f67695810a434de2af182783cbd167e9.avif?1723917209"
max_copies = 4
inkwell = true
strength = 3
willpower = 7
lore = 2
classifications = ["Storyborn", "Ally", "Fairy"]
