name = "Scar - Vicious Cheater"
type = "Character"
cost = 7
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_02f5f28e11b84721906692f042d0baee.avif?1709690747"
max_copies = 4
strength = 6
willpower = 5
lore = 2
classifications = ["Storyborn", "Villain"]
keywords = ["Rush"]
text = "Rush (This character can challenge the turn they're played.)\nDADDY ISN'T HERE TO SAVE YOU During your turn, whenever this character banishes another character in a challenge, you may ready this character. He can't quest for the rest of this turn."
