name = "Winnie the Pooh - Having a Think"
type = "Character"
cost = 3
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_c4dbd53e73ce43b4aa66cbc1fd93885f.avif?1709690747"
max_copies = 4
inkwell = true
strength = 2
willpower = 3
lore = 2
classifications = ["Storyborn", "Hero"]
text = "HUNNY POT Whenever this character quests, you may put a card from your hand into your inkwell facedown."
