name = "Magic Broom - Industrial Model"
type = "Character"
cost = 3
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_e3b8971a2d4140a79429277295edc4eb.avif?1709690747"
max_copies = 4
inkwell = true
strength = 2
willpower = 3
lore = 1
classifications = ["Dreamborn", "Broom"]
text = "MAKE IT SHINE When you play this character, chosen character gains Resist +1 until the start of your next turn. (Damage dealt to them is reduced by 1.)"
