name = "World's Greatest Criminal Mind"
type = "Song"
cost = 3
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_1f27fecaf7074061abaaf6684bce4e2f.avif?1709690747"
max_copies = 4
inkwell = true
text = "(A character with cost 3 or more can {E} to sing this song for free.)\nBanish chosen character with 5 {S} or more."
