name = "HeiHei - Persistent Presence"
type = "Character"
cost = 2
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_907f9d8972fd47b6903590bd53f1e662.avif?1709690747"
max_copies = 4
inkwell = true
strength = 2
willpower = 1
lore = 1
classifications = ["Dreamborn", "Ally"]
text = "HE'S BACK! When this character is banished in a challenge, return this card to your hand."
