name = "Dopey - Always Playful"
type = "Character"
cost = 3
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_45bf84f2a90e48be812c82d9c9272438.avif?1709690747"
max_copies = 4
inkwell = true
strength = 2
willpower = 2
lore = 1
classifications = ["Storyborn", "Ally", "Seven Dwarfs"]
text = "ODD ONE OUT When this character is banished, your other Seven Dwarfs characters get +2 {S} until the start of your next turn."
