name = "Pain - Underworld Imp"
type = "Character"
cost = 2
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_756eca11fdec48c2bc3b4f427b151b6e.avif?1709690747"
max_copies = 4
inkwell = true
strength = 1
willpower = 4
lore = 1
classifications = ["Storyborn", "Ally"]
text = "COMING, YOUR MOST LUGUBRIOUSNESS While this character has 5 {S} or more, he gets +2 {L}."
