name = "Syndrome - Evil Inventor"
type = "Character"
cost = 3
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_6a4abcb645cf41f282d3e6466283ea8d.avif?1777687718"
max_copies = 4
inkwell = true
strength = 4
willpower = 3
lore = 1
classifications = ["Storyborn", "Super", "Villain", "Inventor"]
text = "Alert (This character can challenge as if they had Evasive.)"
