name = "Zipper - Big Helper"
type = "Character"
cost = 4
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_a7f1e4a1087a438a98d149bb5c4e508b.avif?1777687745"
max_copies = 4
inkwell = true
strength = 0
willpower = 6
lore = 2
classifications = ["Floodborn", "Ally"]
keywords = ["Shift 2"]
text = "Shift 2 {I} (You may pay 2 {I} to play this on top of one of your characters named Zipper.)\nBUZZING ENTHUSIASM Whenever this character quests, you may add his {W} to another chosen character's {S} this turn."
