name = "Elinor - Bespelled Queen"
type = "Character"
cost = 4
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_0a71c3e50580448eabd6ee24d079ecad.avif?1777687355"
max_copies = 4
inkwell = true
strength = 3
willpower = 4
lore = 2
classifications = ["Storyborn", "Queen"]
keywords = ["Challenger 2"]
text = "Challenger +2 (While challenging, this character gets +2 {S}.)"
