name = "Frozone - Super Cool"
type = "Character"
cost = 6
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_c36df8a0b082402b95a4545e874435f0.avif?1777687392"
max_copies = 4
strength = 6
willpower = 4
lore = 2
classifications = ["Storyborn", "Super", "Hero"]
keywords = ["Rush"]
text = "Rush (This character can challenge the turn they're played.)\nJUST CHILL When you play this character, if you have another Super character in play, you may exert chosen opposing character."
