//! A self-describing reference for the card-effect DSL (the `[[abilities]]` /
//! `[[activated]]` / `[[statics]]` grammar authored in `cards/<set>/*.toml`).
//!
//! This is the single source for the human/AI-facing syntax doc
//! (`docs/dsl/EFFECT_DSL.md`, generated by the `dsl_reference` binary). It is kept
//! honest by `tests/dsl_reference.rs`, which checks that:
//!   - the committed doc equals [`reference_markdown`] (no drift),
//!   - every effect-verb example below actually parses (no stale syntax), and
//!   - every verb / trigger / restriction / scope the parser recognises is listed.
//!
//! When you add or change DSL syntax, update the tables here and regenerate the
//! doc (`cargo run --bin dsl_reference`).

/// One documented DSL element: a token/verb, a one-line description, and a TOML
/// `example` that must parse (for verbs the example is the `do` effect table).
#[derive(Debug, Clone, Copy)]
pub struct Entry {
    /// The token or verb name.
    pub name: &'static str,
    /// What it does (one line).
    pub about: &'static str,
    /// A parseable example — for an effect verb, the `do = <example>` table.
    pub example: &'static str,
}

/// Effect verbs usable inside a `do = { … }` (or an item of a `do = [ … ]`
/// sequence). Each `example` is a complete effect table.
#[must_use]
#[allow(clippy::too_many_lines)] // a flat data table, one row per verb
pub fn effect_verbs() -> Vec<Entry> {
    vec![
        Entry {
            name: "draw",
            about: "Draw N cards (optional `who` scope, default you).",
            example: "{ draw = 2 }",
        },
        Entry {
            name: "gain_lore",
            about: "A player gains lore (default you).",
            example: "{ gain_lore = 1 }",
        },
        Entry {
            name: "lose_lore",
            about: "A player loses lore (default each opponent).",
            example: "{ lose_lore = 1, who = \"each opponent\" }",
        },
        Entry {
            name: "deal_damage",
            about: "Deal N damage to a target.",
            example: "{ deal_damage = 2, target = \"chosen character\" }",
        },
        Entry {
            name: "remove_damage",
            about: "Remove N damage from a target.",
            example: "{ remove_damage = 2, target = \"chosen character\" }",
        },
        Entry {
            name: "give_strength",
            about: "Change a target's {S} this turn (may be negative).",
            example: "{ give_strength = 2, target = \"chosen character\" }",
        },
        Entry {
            name: "give_willpower",
            about: "Change a target's {W} this turn.",
            example: "{ give_willpower = 1, target = \"chosen character\" }",
        },
        Entry {
            name: "give_lore",
            about: "Change a target's {L} this turn.",
            example: "{ give_lore = 1, target = \"chosen character\" }",
        },
        Entry {
            name: "banish",
            about: "Banish the target.",
            example: "{ banish = \"chosen character\" }",
        },
        Entry {
            name: "exert",
            about: "Exert the target.",
            example: "{ exert = \"chosen opposing character\" }",
        },
        Entry {
            name: "ready",
            about: "Ready the target.",
            example: "{ ready = \"self\" }",
        },
        Entry {
            name: "freeze",
            about: "Freeze the target (can't ready next turn).",
            example: "{ freeze = \"chosen opposing character\" }",
        },
        Entry {
            name: "boost",
            about: "Put the top N cards of your deck face-down under this character (§10.4).",
            example: "{ boost = 1 }",
        },
        Entry {
            name: "prevent_next_damage",
            about: "The next time the target would be dealt damage, it takes none (§7.7).",
            example: "{ prevent_next_damage = \"chosen character\" }",
        },
        Entry {
            name: "return_to_hand",
            about: "Return a target permanent to its owner's hand (§8).",
            example: "{ return_to_hand = \"chosen character\" }",
        },
        Entry {
            name: "return_from_discard",
            about: "Return a card matching a selector from your discard to hand.",
            example: "{ return_from_discard = \"a character\" }",
        },
        Entry {
            name: "into_inkwell",
            about: "Put a target into its owner's inkwell.",
            example: "{ into_inkwell = \"chosen item\" }",
        },
        Entry {
            name: "inkwell_from_hand",
            about: "Put a card matching a selector from your hand into your inkwell.",
            example: "{ inkwell_from_hand = \"a card\" }",
        },
        Entry {
            name: "discard",
            about: "A player discards N cards from hand (default you choose).",
            example: "{ discard = 1, who = \"each opponent\" }",
        },
        Entry {
            name: "play_free",
            about: "Play a card matching a selector from your hand for free (§6).",
            example: "{ play_free = \"a character\" }",
        },
        Entry {
            name: "search",
            about: "Search your deck for up to `take` cards matching the filter; shuffle.",
            example: "{ search = \"a character\", take = 1 }",
        },
        Entry {
            name: "look_at_top",
            about: "Look at the top N; take up to `take` matching to hand; `rest` = bottom|top|shuffle.",
            example: "{ look_at_top = 4, take = \"a song\", rest = \"bottom\" }",
        },
        Entry {
            name: "move_damage",
            about: "Move N damage counters `from` one target `to` another.",
            example: "{ move_damage = 2, from = \"chosen character\", to = \"self\" }",
        },
        Entry {
            name: "grant_keyword",
            about: "Grant a keyword to a target (`duration` = this_turn|next_turn|permanent).",
            example: "{ grant_keyword = \"Evasive\", target = \"self\", duration = \"this_turn\" }",
        },
        Entry {
            name: "restrict",
            about: "Grant a restriction (see Restrictions) to a target, for a `duration`.",
            example: "{ restrict = \"cant_quest\", target = \"chosen opposing character\" }",
        },
        Entry {
            name: "if_you_have",
            about: "Resolve `then` only if you control `at_least` (default 1) matching characters.",
            example: "{ if_you_have = \"a Villain character\", at_least = 2, then = { draw = 1 } }",
        },
        Entry {
            name: "if_count",
            about: "Resolve `then` only if a count condition holds (e.g. cards in hand).",
            example: "{ if_count = \"more than 3 cards in your hand\", then = { draw = 1 } }",
        },
        Entry {
            name: "choose_one",
            about: "Choose one of 2+ sub-effects to resolve (`optional` to allow none).",
            example: "{ choose_one = [ { draw = 1 }, { gain_lore = 1 } ] }",
        },
        Entry {
            name: "may_choose_one",
            about: "Optional `choose_one` (you may decline).",
            example: "{ may_choose_one = [ { draw = 1 }, { gain_lore = 1 } ] }",
        },
        Entry {
            name: "then_to",
            about: "Resolve `apply_to` once, then apply each listed effect to that target (§ `OnTarget`).",
            example: "{ apply_to = \"chosen character\", then_to = [ { exert = \"self\" }, { freeze = \"self\" } ] }",
        },
    ]
}

/// `on = "…"` trigger tokens for `[[abilities]]`.
#[must_use]
pub fn triggers() -> Vec<(&'static str, &'static str)> {
    vec![
        ("play", "When you play this card."),
        ("play_this", "Alias of `play`."),
        ("play_with_shift", "When you play this card using Shift."),
        ("play_character", "Whenever you play a character."),
        ("play_action", "Whenever you play an action."),
        ("play_song", "Whenever you play a song."),
        ("play_item", "Whenever you play an item."),
        ("play_location", "Whenever you play a location."),
        ("quest", "When this character quests."),
        ("challenge", "When this character challenges."),
        ("challenged", "When this character is challenged."),
        ("banish", "When this character is banished."),
        ("banished_in_challenge", "When banished in a challenge."),
        (
            "banishes_in_challenge",
            "When this banishes another in a challenge.",
        ),
        ("start_of_turn", "At the start of your turn."),
        ("end_of_turn", "At the end of your turn."),
        ("draw", "When you draw a card (`you_draw`)."),
        (
            "card_put_in_inkwell",
            "When a card is put into your inkwell.",
        ),
    ]
}

/// Target / selector grammar (the `target` / `to` / `from` strings).
#[must_use]
pub fn selectors() -> Vec<(&'static str, &'static str)> {
    vec![
        ("self / this", "The source card itself."),
        (
            "chosen [opposing|your] [Classification] character",
            "A chosen character, optionally filtered by side/classification.",
        ),
        (
            "another chosen character",
            "Excludes the source (`Not(IsSource)`).",
        ),
        (
            "all your/opposing characters",
            "Every matching character (no choice).",
        ),
        (
            "chosen item / chosen location",
            "A chosen permanent of that kind.",
        ),
        (
            "the challenging / challenged character",
            "The other combatant bound by a challenge trigger.",
        ),
        ("named \"X\"", "Predicate: card name contains X."),
        (
            "with cost N or less/more",
            "Numeric threshold on cost / {S} / {W} / {L}.",
        ),
        (
            "a/an … card",
            "A printed-card filter (e.g. for play_free / search / return_from_discard).",
        ),
    ]
}

/// Dynamic `Amount` strings usable wherever a number is expected.
#[must_use]
pub fn amounts() -> Vec<(&'static str, &'static str)> {
    vec![
        ("<integer>", "A fixed amount."),
        (
            "\"per <filter>\"",
            "One for each matching character (e.g. \"per your Villain character\").",
        ),
        ("\"cards in hand\"", "Your current hand size."),
        ("\"damage on self\"", "Damage counters on the source."),
        ("\"<strength|willpower|lore>\"", "A stat of the source."),
        (
            "\"that much\" / \"damage dealt\"",
            "The amount the trigger carries.",
        ),
    ]
}

/// `who` / `whose` player-scope strings.
#[must_use]
pub fn scopes() -> Vec<(&'static str, &'static str)> {
    vec![
        ("you / yourself", "The controller."),
        ("each opponent / opponents", "Every opponent."),
        ("each player / all players", "Everyone."),
        (
            "chosen opponent",
            "One opponent (auto-resolved in 2-player).",
        ),
        ("chosen player", "One player."),
    ]
}

/// `duration` values for grant/restrict effects.
#[must_use]
pub fn durations() -> Vec<(&'static str, &'static str)> {
    vec![
        ("this_turn", "Until end of turn (default)."),
        ("next_turn", "Until the end of your next turn."),
        ("permanent", "While the source is in play."),
    ]
}

/// `restrict = "…"` restriction tokens.
#[must_use]
pub fn restrictions() -> Vec<(&'static str, &'static str)> {
    vec![
        ("cant_quest", "Can't quest."),
        ("cant_challenge", "Can't challenge."),
        ("cant_be_challenged", "Can't be challenged."),
        ("cant_be_chosen", "Can't be chosen by opponents (Ward)."),
        ("cant_ready", "Doesn't ready during the ready step."),
        (
            "takes_no_challenge_damage",
            "Takes no damage when challenging/challenged.",
        ),
    ]
}

fn table(rows: &[(&str, &str)]) -> String {
    use std::fmt::Write;
    let mut s = String::from("| Token | Meaning |\n| --- | --- |\n");
    for (k, v) in rows {
        let _ = writeln!(s, "| `{k}` | {v} |");
    }
    s
}

/// The ability-table structure sections (triggered / activated / static / §7.7).
fn structures_md() -> String {
    let mut s = String::new();
    s.push_str("## Triggered abilities — `[[abilities]]`\n\n");
    s.push_str(
        "`on` selects the trigger; `do` is one effect table or an array (resolved in \
         order); `may = true` makes it \"you may\"; `during_your_turn` / \
         `during_opponents_turn` gate when it fires.\n\n",
    );
    s.push_str(
        "```toml\n[[abilities]]\non = \"play\"\ndo = [{ draw = 1 }, { gain_lore = 1 }]\n```\n\n",
    );
    s.push_str("### Triggers (`on`)\n\n");
    s.push_str(&table(&triggers()));
    s.push('\n');

    s.push_str("## Activated abilities — `[[activated]]`\n\n");
    s.push_str("A `cost` (`{ exert = true, ink = 1, banish = false }`) plus a `do` effect.\n\n");
    s.push_str(
        "```toml\n[[activated]]\ncost = { exert = true, ink = 1 }\ndo = { draw = 1 }\n```\n\n",
    );

    s.push_str("## Static abilities — `[[statics]]`\n\n");
    s.push_str(
        "A continuous stat modifier: one of `strength` / `willpower` / `lore` on a `to` \
         selector, optionally scaled (`per = \"<filter>\"`) or gated (`while = \"exerted\"`).\n\n",
    );
    s.push_str("```toml\n[[statics]]\nstrength = 1\nto = \"your other Hero characters\"\n```\n\n");

    s.push_str("## §7.7 replacements\n\n");
    s.push_str(
        "`[[redirect_damage]]` (`from = \"<selector>\"`) redirects matching damage onto \
         this card; `[[prevent_damage]]` (`to = \"<selector>\"`, `\"this\"` for itself) \
         prevents it.\n\n",
    );
    s
}

/// The vocabulary tables (verbs / selectors / amounts / scopes / durations / restrictions).
fn vocab_md() -> String {
    use std::fmt::Write;
    let mut s = String::new();
    s.push_str("## Effect verbs (`do`)\n\n");
    s.push_str("| Verb | Meaning | Example |\n| --- | --- | --- |\n");
    for e in effect_verbs() {
        let _ = writeln!(s, "| `{}` | {} | `{}` |", e.name, e.about, e.example);
    }
    s.push_str("\n## Target selectors (`target` / `to` / `from`)\n\n");
    s.push_str(&table(&selectors()));
    s.push_str("\nA leaf may also be the structured AST form (a TOML table) when the compact grammar can't express it.\n\n");
    s.push_str("## Amounts (any numeric field)\n\n");
    s.push_str(&table(&amounts()));
    s.push_str("\n## Player scopes (`who` / `whose`)\n\n");
    s.push_str(&table(&scopes()));
    s.push_str("\n## Durations (`duration`)\n\n");
    s.push_str(&table(&durations()));
    s.push_str("\n## Restrictions (`restrict`)\n\n");
    s.push_str(&table(&restrictions()));
    s
}

/// Render the full DSL reference as Markdown (the committed `docs/dsl/EFFECT_DSL.md`).
#[must_use]
pub fn reference_markdown() -> String {
    let mut s = String::new();
    s.push_str("# Effect DSL reference\n\n");
    s.push_str(
        "GENERATED — do not edit by hand. Run `cargo run --bin dsl_reference` to \
         regenerate from `src/domain/cards/dsl_reference.rs`. This is the authoritative \
         syntax for authoring card abilities in the per-card files \
         (`cards/<set>/<collector>.toml`); the grammar lives in \
         `src/domain/cards/dsl.rs`.\n\n",
    );
    s.push_str(
        "Abilities are authored at the top level of a per-card file; \
         `combine_sets.py` re-nests them under `card.` for the loader.\n\n",
    );
    s.push_str(&structures_md());
    s.push_str(&vocab_md());
    s
}
