name = "Rapunzel - Letting Down Her Hair"
type = "Character"
cost = 6
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_3be63bf0c46342acb7d08759788757b6.avif?1709690747"
max_copies = 4
strength = 5
willpower = 4
lore = 2
classifications = ["Dreamborn", "Hero", "Princess"]
text = "TANGLE When you play this character, each opponent loses 1 lore."
