name = "Tangle"
type = "Action"
cost = 2
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_6e0a4c7a191f4e6fbdc58193e35bbc7c.avif?1709690747"
max_copies = 4
inkwell = true
text = "Each opponent loses 1 lore."
