name = "A Whole New World"
type = "Song"
cost = 5
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_3a299da6bf864690a188f07aeb55ffdf.avif?1709690747"
max_copies = 4
text = "(A character with cost 5 or more can {E} to sing this song for free.)\nEach player discards their hand and draws 7 cards."
