name = "Beast's Mirror"
type = "Item"
cost = 2
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_8e6dc19330d3414885271a4243ca3da4.avif?1709690747"
max_copies = 4
inkwell = true
text = "SHOW ME {E}, 3 {I} — If you have no cards in your hand, draw a card."
