name = "Stitch - Carefree Surfer"
type = "Character"
cost = 7
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_78e5de38150f48c5b9813c08cc534dfb.avif?1709690747"
max_copies = 4
inkwell = true
strength = 4
willpower = 8
lore = 2
classifications = ["Dreamborn", "Hero", "Alien"]
text = "OHANA When you play this character, if you have 2 or more other characters in play, you may draw 2 cards."
