name = "Jafar - Wicked Sorcerer"
type = "Character"
cost = 4
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_695cab1b70c24a0289cc2d3c2316dfed.avif?1709690747"
max_copies = 4
inkwell = true
strength = 2
willpower = 5
lore = 1
classifications = ["Dreamborn", "Villain", "Sorcerer"]
keywords = ["Challenger 3"]
text = "Challenger +3 (While challenging, this character gets +3 {S}.)"
