name = "Minnie Mouse - Pirate Lookout"
type = "Character"
cost = 3
ink = ["Ruby"]
image = "https://cards.lorcast.io/card/digital/large/crd_0e20ed4554c44df494fcf78ac9ce0239.avif?1730901319"
max_copies = 4
strength = 3
willpower = 2
lore = 1
classifications = ["Dreamborn", "Hero", "Pirate"]
text = "LAND, HO! Once during your turn, whenever a card is put into your inkwell, you may return a location card from your discard to your hand."
