name = "Monterey Jack - Good-Hearted Ranger"
type = "Character"
cost = 4
ink = ["Amber"]
image = "https://cards.lorcast.io/card/digital/large/crd_f20ba045e5754b24b0c431115ab83dd8.avif?1730901319"
max_copies = 4
inkwell = true
strength = 0
willpower = 7
lore = 2
classifications = ["Storyborn", "Ally"]
