name = "Yokai - Enigmatic Inventor"
type = "Character"
cost = 4
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_aa952f818e964c30b5d4be10e3654474.avif?1730901319"
max_copies = 4
inkwell = true
strength = 3
willpower = 3
lore = 2
classifications = ["Storyborn", "Villain", "Inventor"]
text = "TIME TO UPGRADE Whenever this character quests, you may return one of your items to your hand to pay 2 {I} less for the next item you play this turn."
