name = "Twin Fire"
type = "Action"
cost = 2
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_7f56bbeab3ce4593beb4feea23724b82.avif?1730901319"
max_copies = 4
text = "Deal 2 damage to chosen character. Then, you may choose and discard a card to deal 2 damage to another chosen character."
