name = "King's Sensor Core"
type = "Item"
cost = 3
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_4d8747b6f80e4bc5a39ace7edc6df9da.avif?1730901319"
max_copies = 4
inkwell = true
text = "SYMBOL OF ROYALTY Your Prince and King characters gain Resist +1. (Damage dealt to them is reduced by 1.)\nROYAL SEARCH {E}, 2 {I} – Reveal the top card of your deck. If it's a Prince or King character card, you may put that card into your hand. Otherwise, put it on the top of your deck."
