name = "Training Dummy"
type = "Item"
cost = 2
ink = ["Steel"]
image = "https://cards.lorcast.io/card/digital/large/crd_513288f8ceec405e9b17fafcb0f5523a.avif?1730901319"
max_copies = 4
inkwell = true
text = "HANDLE WITH CARE {E}, 2 {I} – Chosen character gains Bodyguard until the start of your next turn. (An opposing character who challenges one of your characters must choose one with Bodyguard if able.)"
