name = "Scar - Tempestuous Lion"
type = "Character"
cost = 6
ink = ["Amethyst"]
image = "https://cards.lorcast.io/card/digital/large/crd_6cd588941df64ee2a38738b7f7e23c6a.avif?1730901319"
max_copies = 4
strength = 4
willpower = 4
lore = 2
classifications = ["Dreamborn", "Villain", "Sorcerer"]
keywords = ["Challenger 3", "Rush"]
text = "Rush (This character can challenge the turn they're played.)\nChallenger +3 (While challenging, this character gets +3 {S}.)"
