name = "Basil - Disguised Detective"
type = "Character"
cost = 6
ink = ["Emerald"]
image = "https://cards.lorcast.io/card/digital/large/crd_1ee71443799d40dfb924b0c0f041ea5d.avif?1730901319"
max_copies = 4
inkwell = true
strength = 4
willpower = 5
lore = 2
classifications = ["Floodborn", "Hero", "Detective"]
keywords = ["Shift 4"]
text = "Shift 4 (You may pay 4 {I} to play this on top of one of your characters named Basil.)\nTWISTS AND TURNS During your turn, whenever a card is put into your inkwell, you may pay 1 {I} to have chosen opponent choose and discard a card."
