name = "Four Dozen Eggs"
type = "Song"
cost = 4
ink = ["Sapphire"]
image = "https://cards.lorcast.io/card/digital/large/crd_8b31286860cf4d2da0374f76bf93e6e7.avif?1728609660"
max_copies = 4
inkwell = true
text = "(A character with cost 4 or more can {E} to sing this song for free.)\nYour characters gain Resist +2 until the start of your next turn. (Damage dealt to them is reduced by 2.)"
